name: Proyecto final CI/CD con MLflow

on:
  push:
    branches: [master]

jobs:
  ml_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Clonar repositorio
        uses: actions/checkout@v3

      - name: ðŸ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ðŸ“¦ Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow joblib scikit-learn pandas gdown

      - name: preprocesamiento
        run: make preprocesSAT

      - name: ðŸ§ª Entrenar modelo
        run: make trainSAT

      - name: âœ… Validar desempeÃ±o del modelo
        run: make validateSAT

      #Desde aca se modifica para guardar en git el artefacto
      - name: ðŸ” Obtener ID de la ejecuciÃ³n
        id: get_run_id
        run: echo "RUN_ID=$(cat mlflow_run_id.txt)" >> $GITHUB_OUTPUT

      #- name: âœ… Validar RUN_ID exportado
      #  run: |
      #    echo "El ID de MLflow capturado es: $ {{ steps.get_run_id.outputs.RUN_ID }}"



      - name: ðŸ“¤ Subir modelo como artefacto (si pasa validaciÃ³n)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: modelo-validado
          # Apunta a la carpeta temporal donde 'download_mlflow_model.py' lo guardÃ³
          path: ./temp_model_artifact/

      #- name: ðŸ“¤ Subir modelo como artefacto (si pasa validaciÃ³n)
      #    i f: success()
      #  uses: actions/upload-artifact@v4
      #  with:
      #     name: modelo-validado
      #     path: model.pkl
